const ENVIRONMENT = {
  DYNAMIC_ID: process.env.NEXT_PUBLIC_DYNAMIC_ID || "",
  WORLDCOIN_ID: process.env.NEXT_PUBLIC_WORLDCOIN_ID || "",
  WORLDCOIN_KEY: process.env.NEXT_PUBLIC_WORLDCOIN_KEY || "",
  WORLDCOIN_ACTION_ID: process.env.NEXT_PUBLIC_WORLDCOIN_ACTION_ID || "",
  PERMISSIONLESS_API_KEY: process.env.NEXT_PUBLIC_PERMISSIONLESS_API_KEY || "",
};

export default ENVIRONMENT;
